name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx myst-parser nbsphinx sphinx-autodoc-typehints

      - name: Prepare docs folder (if missing)
        run: |
          mkdir -p docs
          if [ ! -f docs/conf.py ]; then
            sphinx-quickstart docs --project "defy" --author "Lorenzo Villa" --release "0.1.0" --quiet --ext-autodoc --ext-viewcode --ext-napoleon
          fi

      - name: Generate API documentation
        run: |
          sphinx-apidoc -o docs ./defy "./defy/**/tests*" "./defy/**/testing*"

      - name: Ensure conf.py has required settings
        run: |
          # overwrite conf.py with the minimal config we need
          cat > docs/conf.py <<'PY'
import os
import sys
sys.path.insert(0, os.path.abspath('../defy'))

project = 'defy'
author = 'Lorenzo Villa'
release = '0.1.0'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'myst_parser',
    'nbsphinx',
    'sphinx_autodoc_typehints',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '**/tests/**', '**/testing/**']

# Use default theme (do not set html_theme)
# html_theme = 'alabaster'  # optional: keep commented to use Sphinx default

# Allow both .rst and .md if you use myst-parser
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}
master_doc = 'index'
PY

      - name: Build HTML docs
        run: |
          sphinx-build -b html docs docs/_build/html -v

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html
